/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import ipc.Factura;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author macoas
 */
public class GestorFacturas extends javax.swing.JFrame {

    private ArrayList<Factura> listaFacturas = new ArrayList<Factura>();

    /**
     * Creates new form GestorFacturas
     */
    public GestorFacturas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        asuntoTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        diaSpinner = new javax.swing.JSpinner();
        mesSpinner = new javax.swing.JSpinner();
        anoSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        cantidadTextField = new javax.swing.JTextField();
        mensajeLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tipoComboBox = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        facturasList = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 137));

        jPanel2.setLayout(new java.awt.GridLayout(4, 0));

        jLabel1.setText("Asunto:");
        jPanel2.add(jLabel1);
        jPanel2.add(asuntoTextField);
        jPanel2.add(jLabel5);
        jPanel2.add(jLabel4);

        jLabel2.setText("Fecha:");
        jPanel2.add(jLabel2);

        diaSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        diaSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                diaSpinnerStateChanged(evt);
            }
        });
        jPanel2.add(diaSpinner);

        mesSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        mesSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mesSpinnerStateChanged(evt);
            }
        });
        jPanel2.add(mesSpinner);

        anoSpinner.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, 3000, 1));
        jPanel2.add(anoSpinner);

        jLabel3.setText("Cantidad:");
        jPanel2.add(jLabel3);
        jPanel2.add(cantidadTextField);
        jPanel2.add(mensajeLabel);
        jPanel2.add(jLabel6);

        jLabel7.setText("Tipo");
        jPanel2.add(jLabel7);

        tipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empresas", "Particulares" }));
        jPanel2.add(tipoComboBox);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        errorLabel.setForeground(new java.awt.Color(204, 0, 0));
        jPanel4.add(errorLabel);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(facturasList);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(3, 1));

        addButton.setText("Añadir/Actualizar");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel3.add(addButton);

        editButton.setText("Editar");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel3.add(editButton);

        removeButton.setText("Eliminar");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        jPanel3.add(removeButton);

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        String value = this.facturasList.getSelectedValue();
        if (value != null) {
            String asunto = value.split(":")[0];
            Factura factura = getFactura(asunto);
            if (factura != null) {
                this.asuntoTextField.setText(factura.getAsunto());
                this.diaSpinner.setValue(factura.getFecha().getDayOfMonth());
                this.mesSpinner.setValue(factura.getFecha().getMonthValue());
                this.anoSpinner.setValue(factura.getFecha().getYear());
                this.tipoComboBox.setSelectedItem(factura.getTipo());
            }
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        if (camposEntradaValidos()) {

            String asunto = this.asuntoTextField.getText();
            int dia = (int) diaSpinner.getValue();
            int mes = (int) mesSpinner.getValue();
            int ano = (int) anoSpinner.getValue();
            double cantidad = Double.parseDouble(cantidadTextField.getText());
            String tipo = (String) tipoComboBox.getSelectedItem();
            Factura factura = new Factura(asunto, LocalDate.of(ano, mes, dia), cantidad, tipo);
            if (!this.listaFacturas.contains(factura)) {
                this.listaFacturas.add(factura);
                errorLabel.setText("Factura añadida con éxito");
            } else {
                factura = getFactura(asunto);
                factura.setFecha(LocalDate.of(ano, mes, dia));
                factura.setCantidad(cantidad);
                factura.setTipo(tipo);
                errorLabel.setText("Factura actualizada con éxito");
            }
            actualizarListaFacturas();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        String value = this.facturasList.getSelectedValue();
        if (value != null) {
            String asunto = value.split(":")[0];
            Factura factura = getFactura(asunto);
            this.listaFacturas.remove(factura);
            errorLabel.setText("Factura eliminada con éxito");
        }
        actualizarListaFacturas();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void diaSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_diaSpinnerStateChanged
        // TODO add your handling code here:
        int dia = (int) this.diaSpinner.getValue();

    }//GEN-LAST:event_diaSpinnerStateChanged

    private void mesSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mesSpinnerStateChanged
        // TODO add your handling code here:
        int dia = (int) this.diaSpinner.getValue();
        int mes = (int) this.mesSpinner.getValue();
        SpinnerModel diaModel = new SpinnerNumberModel(dia, 1, getDiaMaximo(mes), 1);
        this.diaSpinner.setModel(diaModel);
    }//GEN-LAST:event_mesSpinnerStateChanged

    private int getDiaMaximo(int mes) {
        switch (mes) {
            case 2:
                return 28;
            case 4:
                return 30;
            case 6:
                return 30;
            case 9:
                return 30;
            case 11:
                return 30;
            default:
                return 31;
        }
    }

    private void actualizarListaFacturas() {
        DefaultListModel<String> modelo = new DefaultListModel<>();
        for (Factura factura : this.listaFacturas) {
            modelo.addElement(factura.toString());
        }
        facturasList.setModel(modelo);
    }

    private Factura getFactura(String asunto) {
        for (Factura factura : this.listaFacturas) {
            if (asunto.equals(factura.getAsunto())) {
                return factura;
            }
        }
        return null;
    }

    private boolean camposEntradaValidos() {
        String asunto = this.asuntoTextField.getText();
        if (asunto.isEmpty() || asunto.length() > 10) {
            errorLabel.setText("El asunto debe tener entre 1 y 10 caractéres");
            return false;
        }
        try {
            double cantidad = Double.parseDouble(cantidadTextField.getText());
            if (cantidad < 0) {
                errorLabel.setText("La cantidad debe ser un número positivo");
                return false;
            }
        } catch (Exception e) {
            errorLabel.setText("La cantidad debe ser un número positivo");
            return false;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorFacturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JSpinner anoSpinner;
    private javax.swing.JTextField asuntoTextField;
    private javax.swing.JTextField cantidadTextField;
    private javax.swing.JSpinner diaSpinner;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JList<String> facturasList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mensajeLabel;
    private javax.swing.JSpinner mesSpinner;
    private javax.swing.JButton removeButton;
    private javax.swing.JComboBox<String> tipoComboBox;
    // End of variables declaration//GEN-END:variables
}
